- name: software | bitwarden | install package
  tags: bitwarden,packages,flatpak,workstation-packages
  become_user: jay
  flatpak:
    name: flathub com.bitwarden.desktop
    method: user
    state: present
  when: bitwarden is defined and bitwarden == true
