- name: software | libreoffice | install package
  tags: packages,flatpak,libreoffice,workstation-packages
  become_user: jay
  flatpak:
    name: org.libreoffice.LibreOffice
    method: user
    state: present
  when: libreoffice is defined and libreoffice == true
