autofs_master_config: /etc/autofs/auto.master
autofs_nfs_config: /etc/autofs/auto.nfs
cryptsetup_package: cryptsetup
cups_package: cups
font_fira_mono_package: otf-fira-mono
font_hack_ttf_package: ttf-hack
font_inconsolata_package: ttf-inconsolata
font_noto_emoji_package: noto-fonts-emoji
font_terminus_package: terminus-font
gdm_package: gdm
gstreamer_libav_package: gst-libav
gstreamer_plugins_bad_package: gst-plugins-bad-libs
hunspell_package: hunspell-en_US
hyphen_package: hyphen-en
jay_user_group: users
libnotify_package: libnotify
mpv_package: mpv
nethack_package: nethack
network_manager_openvpn_package: networkmanager-openvpn
network_manager_package: networkmanager
network_manager_pptp_package: networkmanager-pptp
network_manager_vpnc_package: networkmanager-vpnc
p7zip_package: p7zip
packer_version: 1.6.5
ssh_askpass_package: x11-ssh-askpass
steam_package: steam
terraform_version: 0.13.5
vagrant_version: 2.2.14
virtualbox_package: virtualbox
wireless_tools_package: wireless_tools
wpa_supplicant_package: wpa_supplicant
