- name: system setup | scripts | copy image_prep.sh script
  tags: scripts
  copy:
    src: system_setup/image_prep.sh
    dest: /usr/local/bin/image_prep.sh
    owner: root
    group: root
    mode: 0755

- name: system setup | scripts | copy pi_cpu_temp.py script
  tags: scripts
  copy:
    src: system_setup/pi_cpu_temp.py
    dest: /usr/local/bin/cpu_temp
    owner: root
    group: root
    mode: 0755
  when: ansible_architecture == "aarch64"
